# Generated by Django 6.0.4 on 2026-04-08 22:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_organizations_city_alter_organizations_email_and_more'),
        ('people', '0003_alter_people_city_alter_people_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='Scheduled', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=25)),
                ('lng', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=25)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
    ]
