# Generated by Django 6.0.2 on 2026-04-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developments',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='scheduled', max_length=10),
        ),
    ]
