# Generated by Django 6.0.3 on 2026-03-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
