# Generated by Django 6.0.4 on 2026-04-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizations_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
