# Generated by Django 6.0.4 on 2026-04-08 22:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donations_donations'),
        ('organizations', '0003_alter_organizations_city_alter_organizations_email_and_more'),
        ('people', '0003_alter_people_city_alter_people_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='donations',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='donations',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='people.people'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donate_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
